import json
import boto3
import os

#Evaluates the challenge generated by resumeGenerateChallengeLambda.py
#Displays contact info on successful evaluation

#Get environment variables for DynamoDB table and SSM parameters
table_name = os.environ['tableName']
contact_email_parameter = os.environ['contactEmailParameter']
contact_phone_parameter = os.environ['contactPhoneParameter']

dyn_db_client = boto3.client('dynamodb')
ssm_client = boto3.client('ssm')

def lambda_handler(event, context):
    #Set vars from event query string
    requestId = event['queryStringParameters']['reqId']
    userSolution = event['queryStringParameters']['solution']
    
    #gets the solution from the requestId
    get_solution = dyn_db_client.get_item(
        TableName=table_name,
        Key={
            'reqId': {
                'S': str(requestId)
            }
        }
    )
    
    #deletes the solution because it was used already
    dyn_db_client.delete_item(
        TableName=table_name,
        Key={
            'reqId': {
                'S': str(requestId)
            }
        }
    )
    
    #parse just the solution
    solution = get_solution['Item']['solution']['N']
    
    #checks user solution vs correct solution and fetches contact parameters if successful
    if int(solution) == int(userSolution):
        get_email = ssm_client.get_parameter(
            Name=contact_email_parameter
        )
        
        get_phone = ssm_client.get_parameter(
            Name=contact_phone_parameter
        )
        
        email = get_email['Parameter']['Value']
        phone = get_phone['Parameter']['Value']
        
    else:
        email = "try"
        phone = "again"

    #returns contact info or try again
    response = {
        'statusCode': 200,
        'headers': {
            'Access-Control-Allow-Headers': 'Content-Type',
            'Access-Control-Allow-Origin': '*.mattisz.com/*',
            'Access-Control-Allow-Methods': 'OPTIONS,POST,GET',
            'Content-Type': 'application/json'
        },
        'body': json.dumps({
            'email': email,
            'phone': phone
        })
    }

    return response